name: Run tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install dependencies
        run: npm install
      - name: Compile typescript
        run: npm run compile
      - name: Run tests
        run: npm test
